// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXdQDcp-5fb4WSrR63fZ4AiSL9O1qx4yo',
    appId: '1:973194195175:web:93886d74f7c84f10737242',
    messagingSenderId: '973194195175',
    projectId: 'flutterfirebaseshop',
    authDomain: 'flutterfirebaseshop.firebaseapp.com',
    storageBucket: 'flutterfirebaseshop.firebasestorage.app',
    measurementId: 'G-HPE5XDKFPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLaPBpp_pyehM52EnJk3IzAHtuwpHG3uU',
    appId: '1:973194195175:android:d30dca7ed6f5c28e737242',
    messagingSenderId: '973194195175',
    projectId: 'flutterfirebaseshop',
    storageBucket: 'flutterfirebaseshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yKI4I6N4m2JMwKam7_fqBkZF05BKp6M',
    appId: '1:973194195175:ios:eafdba91ee7aad5b737242',
    messagingSenderId: '973194195175',
    projectId: 'flutterfirebaseshop',
    storageBucket: 'flutterfirebaseshop.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1yKI4I6N4m2JMwKam7_fqBkZF05BKp6M',
    appId: '1:973194195175:ios:eafdba91ee7aad5b737242',
    messagingSenderId: '973194195175',
    projectId: 'flutterfirebaseshop',
    storageBucket: 'flutterfirebaseshop.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXdQDcp-5fb4WSrR63fZ4AiSL9O1qx4yo',
    appId: '1:973194195175:web:61bdc03c01d7a4ca737242',
    messagingSenderId: '973194195175',
    projectId: 'flutterfirebaseshop',
    authDomain: 'flutterfirebaseshop.firebaseapp.com',
    storageBucket: 'flutterfirebaseshop.firebasestorage.app',
    measurementId: 'G-SV43GCKDJ9',
  );
}
